Java 16
cpw/serverpacklocator pull request #9
Opened 2022-05-29 17:51 UTC by OrionDevelopment

This provides support for Java 16 by stripping out all the nice stuff, and replacing it with a stupid password.
Far from ideal, but it works...........

2022-05-31 15:54 UTC, Bricktricker reviewed
I have thought about some ways to still achieve some encryption/ authentication.
If I understand it correctly the problem with java 16+ is, we can no longer use classes from the sun.security.* package?

I came up with a few ways to solve this:

### 1. Password based approach
 - Choose a password and share it with all the server users.
 - Derive an AES Key from the shared password ( using [PBEKeySpec](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/javax/crypto/spec/PBEKeySpec.html) )
 - Encrypt all traffic with this key. This has the advantage of not needing to send the password / hash to the server
 
### 2. TLS with manual authentication
 - This would allow ServerPackLocator to still use TLS for its communication, allowing a secure and authenticated way to talk to the server
 - Generate the server certificate with openSSL (or any other library)
 - Don't use the built-in client authentication from TLS, instead manually check the client auth by requiring the client to first send an authentication packet (This could again contain a password, or maybe something else?)
 - This approach has the disadvantage of needing to share a password with all users AND requiring every user to download the server certificate. 
 
### 3. Manually write a certificate builder
 - This approach has the advantage of allowing us to use the full encryption / authentication features of TLS, without needing to deal with them ourselves.
 - X509 certificates are no magic and have relatively simple architecture. I have written a CertificateBuilder [here](https://gist.github.com/Bricktricker/05ad7ce90e3ca607507fcc633fce11d0), that allows the generation of a signed certificate with Java code.
 - Unfortunately this would require finding another solution for the certificate signing request (CSR). Instead of using an offical CSR format, a JSOn format could be used.
   Since ServerPackLocator only needs the client public key and his UUID, this information could get written to a JSON file.

2022-05-31 15:54 UTC, Bricktricker commented on build.gradle
> +java.toolchain.languageVersion = JavaLanguageVersion.of(16)
The utilmod uses Java 17, so I think you can also bump this to 17

2022-05-31 15:54 UTC, Bricktricker commented on src/main/java/cpw/mods/forge/serverpacklocator/server/RequestHandler.java
> +import org.codehaus.plexus.util.Base64;
wrong Base64 converter? Java has its own [converter](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/Base64.html). (Is it even used?)

2022-05-31 15:54 UTC, Bricktricker commented on src/main/java/cpw/mods/forge/serverpacklocator/server/RequestHandler.java
> +            throw new IllegalStateException("Missing MD5 hashing algorithm", e);
MD5 -> SHA-256

2022-05-31 19:37 UTC, OrionDevelopment commented
Just so everybody is on the same page:
This PR is not ment to be merged! It is a starting point for CPW and others to start of, within some of the servers I am part of we needed a working solution and we came up with this, yes it is not perfect, but while the primary maintainer was not available we needed a solution. 
He is back and we have been chatting behind the scenes, and there are ideas as to how to fix this conundrum that Java caused us. Stay tuned for more info.

2022-05-31 19:38 UTC, marchermans commented
> ### 2. TLS with manual authentication
> * This would allow ServerPackLocator to still use TLS for its communication, allowing a secure and authenticated way to talk to the server
> * Generate the server certificate with openSSL (or any other library)
> * Don't use the built-in client authentication from TLS, instead manually check the client auth by requiring the client to first send an authentication packet (This could again contain a password, or maybe something else?)
> * This approach has the disadvantage of needing to share a password with all users AND requiring every user to download the server certificate.

This is basically the setup that this PR creates.
We run this behind an SSL terminating reverse proxy and that is then that. Easy to set up for any admin. That said it is not optimal as there is no client auth included in this setup.

2022-08-29 07:50 UTC, OrionDevelopment commented
@Bricktricker I added support for Mojangs PublicKey system that they added in 1.19.2.
What do you think?

2022-08-30 18:24 UTC, Bricktricker commented
Looks good to me, but im currently on vacation so I can't test it.

2022-09-25 11:23 UTC, Bricktricker requested changes
I got some more time to look at your implementation and I think I found a problem with it.
The client never validates to the server, that it has the private key to the sent public key.
Therefore an attack could capture a valid authentication and then simply always send the captured data. Maybe the server should send a challenge to the client, which the client has to sign, to prove he owns the matching private key? Or another option would be to let the client sign the current time+date to prevent the replay attacks?

The key expire date send from the client to the server is not signed or protected in any way,
so an attacker could simply choose a date in the future and use that as the sent expire date.
To prevent this the server could download the players public Key and expire date from mojang,
but I'm not sure if this is possible.

Could you add the eclipse stuff to the .gitignore file?

2022-09-25 11:23 UTC, Bricktricker commented on src/main/java/cpw/mods/forge/serverpacklocator/client/SimpleHttpClient.java
> +            ReadableByteChannel channel = Channels.newChannel(connection.getInputStream());
The `channel` and `download` objects never get closed

2022-09-25 11:23 UTC, Bricktricker commented on src/main/java/cpw/mods/forge/serverpacklocator/secure/ConnectionSecurityManager.java
> +        final IConnectionSecurityManager connectionSecurityManager = securityManagers.get(securityType);
Maybe add a check if `securityType` is a valid security manager and otherwise print a helpfull error message?

2022-09-25 11:23 UTC, Bricktricker commented on src/main/java/cpw/mods/forge/serverpacklocator/secure/ProfileKeyPairBasedSecurityManager.java
> +    private final UUID sessionId;
I would rename this to something like `playerId` (and everywhere else in this class), because it's just the uuid of the player

2022-09-25 11:23 UTC, Bricktricker commented on src/main/java/cpw/mods/forge/serverpacklocator/secure/ProfileKeyPairBasedSecurityManager.java
> +    private static byte[] buildMessageHashFromSignature(final UUID sessionId)
I think `hashUUID` is a better name for this method

2022-09-25 11:23 UTC, Bricktricker commented on src/main/java/cpw/mods/forge/serverpacklocator/server/SimpleHttpServer.java
> +                        ch.pipeline().addLast("request", new RequestHandler(handler, ProfileKeyPairBasedSecurityManager.getInstance()));
Hardcoded security manager

2022-09-25 11:23 UTC, Bricktricker commented on src/main/resources/defaultclientconfig.toml
>  remoteServer = "https://localhost:8080/"
WE should change protocol to `http`, because we no longer use TLS

2022-09-25 16:59 UTC, OrionDevelopment commented
> I got some more time to look at your implementation and I think I found a problem with it. The client never validates to the server, that it has the private key to the sent public key. Therefore an attack could capture a valid authentication and then simply always send the captured data. Maybe the server should send a challenge to the client, which the client has to sign, to prove he owns the matching private key? Or another option would be to let the client sign the current time+date to prevent the replay attacks?
> 
> The key expire date send from the client to the server is not signed or protected in any way, so an attacker could simply choose a date in the future and use that as the sent expire date. To prevent this the server could download the players public Key and expire date from mojang, but I'm not sure if this is possible.
> 
> Could you add the eclipse stuff to the .gitignore file?

Currently I am signing the session ID as a temporal value. It changes every restart. But that indeed seems limited.
That said, a signed nonce would indeed be much better but would require the server to hold on to it somehow possible? Or would it suffice if the client sends it back in plain text and a signed variant to prove that it has the private key.

In understand the technical reason you would want this, but in these kinds of scenarios I am not a fan of using time as a signing component, since that is complicated to validate on a signature level.....

2022-09-28 12:48 UTC, Bricktricker commented
Not sure why you think the session id changes every restart?
You read the `--uuid` and `--accessToken` arguments at launch. The access token can change between sessions,
but the uuid is always the same.

To use a nonce I would change the protocol as following:
- For every connection the server stores a unique nonce and an authenticated flag.
- First the client has to request the nonce. He then has to sign the nonce with his private key.
and sends the signature back with the other headers (add a `Nonce-Signature` header [here](https://github.com/OrionDevelopment/serverpacklocator/blob/4496cf9ba45515b286bde1a3a79513e75b69754e/src/main/java/cpw/mods/forge/serverpacklocator/secure/ProfileKeyPairBasedSecurityManager.java#L211-L216))
- The server additionally checks if the signature is valid and updates the authenticated flag.
The client can then continue to request the servermanifest and the mods.

2022-09-28 14:08 UTC, OrionDevelopment commented
> Not sure why you think the session id changes every restart?
> You read the `--uuid` and `--accessToken` arguments at launch. The access token can change between sessions,
> but the uuid is always the same.
> 
> To use a nonce I would change the protocol as following:
> - For every connection the server stores a unique nonce and an authenticated flag.
> - First the client has to request the nonce. He then has to sign the nonce with his private key.
> and sends the signature back with the other headers (add a `Nonce-Signature` header [here](https://github.com/OrionDevelopment/serverpacklocator/blob/4496cf9ba45515b286bde1a3a79513e75b69754e/src/main/java/cpw/mods/forge/serverpacklocator/secure/ProfileKeyPairBasedSecurityManager.java#L211-L216))
> - The server additionally checks if the signature is valid and updates the authenticated flag.
> The client can then continue to request the servermanifest and the mods.
> 

Would it not be better to produce a new nonce for every response?
Like a chain exchange a input request for an output request?

2022-09-30 10:57 UTC, Bricktricker commented
That would work, but not sure if we gain anything from that. If the client can prove he owns the private key at the beginning, the server can be sure he is talking to the correct client.

2022-09-30 15:23 UTC, Bricktricker commented
I have implemented a PoC [here](https://github.com/OrionDevelopment/serverpacklocator/compare/master...Bricktricker:serverpacklocator:master). It works, but I don't really like passing the challenge bytes into the [`onClientConnectionCreation`](https://github.com/Bricktricker/serverpacklocator/blob/634268e312bb68adb163ba953c05f7d4e7e60faa/src/main/java/cpw/mods/forge/serverpacklocator/secure/IConnectionSecurityManager.java#L10)
and [`onServerConnectionRequest`](https://github.com/Bricktricker/serverpacklocator/blob/634268e312bb68adb163ba953c05f7d4e7e60faa/src/main/java/cpw/mods/forge/serverpacklocator/secure/IConnectionSecurityManager.java#L12) methods. Maybe you can find a better solution? I also havent tested if the password based approach still works.

2023-08-05 08:15 UTC, closed without merging